import time
endings=0
def menu():
    print("go into castle (1)")
    print("go into side tower (2)")
    print("go into pit of unbelievable depth (3)")
    print("leave (4)")
    choice=int(input("SO MANY CHOICES!"))
    return choice

print("there is a castle")
print("wooo")
print("I am excited... I dont know about you...")
def play():
    global endings
    sure=False
    before=False
    while sure==False:
        choice=menu()
        print(choice, "?  Are you sure about that? It could be a bit risky!")
        sure1=input("yes or no")
        sure1=sure1.lower()
        yes_or_no=["yes", "no"]
        while sure1 not in yes_or_no:
            print("oh ok \nthat wasnt a choice...")
            sure1=input("yes or no?")
            sure1=sure1.lower()
        if sure1=="yes":
            sure=True
            if choice==1:
                print("you go into the castle!")
                time.sleep(2)
                print("I would have done that too...")
                time.sleep(2)
                print("you enter a courtyard")
                time.sleep(1)
                print("and there is flowers, and trees, and paths")
                time.sleep(2)
                print("wait! paths! an opportunity for the story to develop!")
                time.sleep(3)
                choice=input("do you go down the path or up?")
                print("well too bad because the path isn't vertical")
                time.sleep(2)
                print("you'll have to go left or right instead")
                choice=input("left or right")
                while choice.lower()!="left" and choice.lower()!="right":
                    print("that wasn't a choice... I don't know what you were thinking!")
                    choice=input("left or right?")
                if choice.lower()=="left":
                    print("you went right")
                    time.sleep(3)
                    print("there was-")
                    time.sleep(1)
                    print("wait! no! wrong script!")
                    time.sleep(4)
                    print("I lost the left script around the program somewhere...")
                    time.sleep(3)
                    print("I'll have to make it up as we go!")
                    time.sleep(2)
                    print("so... you went left...")
                    time.sleep(2)
                    print("and there were snakes!")
                    time.sleep(2)
                    print("and you fought them!")
                    time.sleep(2)
                    choice=input("do you hack? or slash?")
                    while choice.lower()!="hack" and choice.lower()!="slash":
                        print("that wasn't a choice... I don't know what you were thinking!")
                        choice=input("do you hack? or slash?")
                    if choice.lower()=="hack":
                        print("you hacked!")
                        time.sleep(2)
                        print("you used your hacking skills to change the snakes into cats!")
                        time.sleep(2)
                        print("you got past!")
                        time.sleep(2)
                        print("as you go by, you find a door\nand use your hacking skills again!")
                        time.sleep(2)
                        print("the door opens and you found a prisoner...")
                        time.sleep(2)
                        choice=input("do you free the prisoner?")
                        while choice != "yes" and choice != "no":
                            print("that wasn't a choice... I don't know what you were thinking!")
                            choice=input("do you free the prisoner?")
                        if choice == "yes":
                            print("you ask the prisoner if he wants to be freed")
                            time.sleep(3)
                            print("he says no")
                            time.sleep(4)
                            print("after an extensive argument over whether it would be good if he were freed or not...")
                            time.sleep(3)
                            print("he decided to go with you")
                            time.sleep(2)
                            print("you both leave the castle and live happily ever after! yay!")
                            time.sleep(3)
                            print("in a shack near the castle")
                            time.sleep(2)
                            print("(saviour ending)")
                            endings=endings+1
                        elif choice == "no":
                            print("you leave the prisoner in the cell\n and throw away the key")
                            time.sleep(2)
                            print("but then feel so guilty you leave then and there")
                            time.sleep(2)
                            print("and 5 years later when the prisoner is freed by someone else")
                            time.sleep(2)
                            print("he kills you in a rage")
                            time.sleep(2)
                            print("(selfish ending)")
                            endings=endings+1
                    elif choice.lower()=="slash":
                         print("you slash at the snakes with your-")
                         time.sleep(2)
                         print("you have no weapon")
                         time.sleep(1)
                         print("but dont worry! there will be something around you can use!")
                         time.sleep(2)
                         print("you look around for a weapon")
                         time.sleep(2)
                         print("you see a sword across the courtyard!")
                         time.sleep(1)
                         print("perfect for slashing!")
                         time.sleep(2)
                         print("however it took you so long to read this...")
                         time.sleep(1)
                         print("that the snakes easily got to you from 2m away")
                         time.sleep(2)
                         print("and now you are dead")
                         time.sleep(2)
                         print("that's a shame")
                         time.sleep(2)
                         print("(bitten ending)")
                         endings=endings+1
                elif choice.lower()=="right":
                    print("you went right")
                    time.sleep(2)
                    print("there was an archway, which you also went through")
                    time.sleep(1)
                    choice=input("didn't you?")
                    while choice != "yes" and choice != "no":
                        print("that wasn't a choice... I don't know what you were thinking!")
                        choice=input("didn't you?")
                    if choice=="yes":
                        print("good")
                    else:
                        print("no you did...")
                        time.sleep(3)
                        print("ok fine you went over the archway")
                        print("(jumpy ending (that isn't even at the end)")
                        endings=endings+1
                    time.sleep(2)
                    print("now you are on the other side of the archway there is a throne room")
                    time.sleep(2)
                    print("with the king in it!")
                    time.sleep(2)
                    print("he asks you if you brought him his coffee")
                    time.sleep(2)
                    print("you think it would be safest to say yes")
                    time.sleep(2)
                    print("funnily enough he doesn't believe you, as you clearly don't have any coffee")
                    time.sleep(3)
                    print("he challenges you to a fight!")
                    time.sleep(2)
                    choice=input("do you attack? or run?")
                    while choice!="attack" and choice!="run":
                        print("that wasn't a choice... I don't know what you were thinking!")
                        choice=input("do you attack? or run?")
                    if choice=="attack":
                        print("you decide to attack the king!")
                        time.sleep(2)
                        print("the fight is long and complex")
                        time.sleep(2)
                        print("and neither of you have weapons")
                        time.sleep(5)
                        print("you win!")
                        time.sleep(2)
                        print("after this you take over the castle and its inhabitants!")
                        time.sleep(2)
                        print("(royal ending)")
                        endings=endings+1
                    else:
                        print("you run away!")
                        time.sleep(2)
                        print("coward!")
                        time.sleep(2)
                        print("now you'll have to make a second approach...")
                        time.sleep(2)
                        print("even if you don't go back to the king")
                        time.sleep(2)
                        print("(coward ending)")
                        endings=endings+1
            elif choice==2:
                end=False
                print("you went into the side tower")
                print("suprise suprise")
                time.sleep(2)
                print("in the tower was stairs")
                time.sleep(2)
                print("otherwise it wouldn't be a tower")
                time.sleep(2)
                print("do you go up?")
                print("or down?")
                choice=input("up or down?")
                while choice=="up":
                    if before==True:
                        print("you really want to go up don't you?")
                        time.sleep(2)
                        print("well fine")
                        time.sleep(2)
                        print("you look around the room... and still see nothing")
                        time.sleep(5)
                        print("but wait! there's an old hermit in the corner")
                        time.sleep(2)
                        print("he wants you to buy his magic ball of air")
                        time.sleep(2)
                        print("he says if you breathe it you become magic")
                        time.sleep(4)
                        print("i wouldn't buy it if I were you...")
                        time.sleep(1)
                        print("but I'm not you... so I'll leave it up to you")
                        buy=input("do you buy the air?")
                        if buy.lower()=="yes":
                            print("congratulations")
                            time.sleep(2)
                            print("you bought the air!")
                            time.sleep(2)
                            print("you exit the tower and go outside the castle,")
                            print("and breathe the air!")
                            time.sleep(4)
                            print("well get on with it! its just air!")
                            time.sleep(5)
                            print("finally! you have breathed")
                            time.sleep(2)
                            print("now you are magic! congratulations!")
                            time.sleep(5)
                            do=input("what will you do?")
                            print("well good luck doing", do)
                            time.sleep(2)
                            print("in the meantime... I will carry on with the story...")
                            print("and you can go into the castle again...")
                            time.sleep(2)
                            print("since you are now outside")
                            time.sleep(2)
                            print("(breathy ending)")
                            endings=endings+1
                            choice=0
                        else:
                            print("unfortunately the hermit stole your money...")
                            time.sleep(2)
                            print("and then threw the air at you")
                            time.sleep(2)
                            print("good job")
                            time.sleep(2)
                            print("(stingy ending)")
                            endings=endings+1
                            end=True
                            break
                    else:
                        print("there was nothing at the top... so you went back down")
                        before=True
                        choice=input("up or down?")
                if choice=="down":
                    print("you went down the stairs")
                    time.sleep(2)
                    print("at the bottom was treasure!")
                    time.sleep(2)
                    print("you notice a hole too... it must be the same one you saw outside the castle...")
                    time.sleep(2)
                    print("you decide to exit with the treasure")
                    time.sleep(2)
                    print("you escape and are rich for the rest of your life")
                    time.sleep(3)
                    print("but never win the lottery even after buying 8.6 million tickets")
                    time.sleep(2)
                    print("(undiscovered ending)")
                    time.sleep(2)
                    print("(as in you were undiscovered... not the ending)")
                    endings=endings+1
                else:
                    if end==False:
                        print("u didnt pick in time and u died...")
                        time.sleep(2)
                        print("just like that")
                        print("(secret ending)")
                        endings=endings+1
            elif choice==3:
                print("at the bottom of the pit was so many treasures!")
                print("if only you could've had these a while ago to pay off that carpenter...")
                time.sleep(3)
                print("now how will you get out of the hole?")
                time.sleep(5)
                print("especially since you died from the great fall")
                time.sleep(3.5)
                print("why did you think it would be a good idea to jump down here")
                time.sleep(2)
                print("and without any equipment or anything...")
                time.sleep(2)
                print("ahh well... have another go!")
                time.sleep(2)
                print("at life... hmmmmm")
                time.sleep(2)
                print("(holy ending)")
                endings=endings+1
            elif choice==4:
                print("ok... bye!")
                print("program.end")
                time.sleep(5)
                print("as you left the castle you notice something along the path...")
                time.sleep(3.5)
                print("it was a-!")
                time.sleep(2)
                print("you died")
                time.sleep(2)
                print("wow that was SUDDEN!")
                time.sleep(2)
                print("i didnt expect that...")
                time.sleep(2)
                print("well i did...")
                time.sleep(2)
                print("i wrote the game...")
                time.sleep(2)
                print("but i bet you didnt expect it!")
                time.sleep(1)
                print("and thats what matters!")
                time.sleep(4)
                print("have another go...")
                time.sleep(2)
                print("(suprise ending)")
                endings=endings+1
        elif sure1=="no":
            print("well fine... change your mind then")
            time.sleep(2)
            print("(unsure ending(that wasn't even at the end))")
            time.sleep(2)
            endings=endings+1

play()
def anothergo():
    global anothergoes
    global endings
    print("so far (since the program has been running) you have", endings, "endings")
    print("(there are 14 different endings)")
    anothergo=input("do you want another go?")
    if anothergo.lower()=="yes":
        play()
    else:
        anothergoes=False
        print("that appeared to be a no...")
        time.sleep(2)
        print("or at least not a yes")
        print("thats the game then!")
        time.sleep(2)
        import turtle
        t=turtle.Turtle()
        t.up()
        t.backward(150)
        t.left(90)
        t.down()
        t.forward(100)
        t.right(90)
        t.forward(50)
        t.backward(50)
        t.right(90)
        t.forward(50)
        t.left(90)
        t.forward(50)
        t.backward(50)
        t.right(90)
        t.forward(50)
        t.left(90)
        t.forward(50)
        t.up()
        t.forward(30)
        t.down()
        t.left(90)
        t.forward(100)
        t.right(150)
        t.forward(120)
        t.left(150)
        t.forward(100)
        t.up()
        t.right(90)
        t.forward(30)
        t.down()
        t.right(90)
        t.forward(100)
        t.left(90)
        t.circle(50,180,30)

        
anothergoes=True
while anothergoes==True:
    anothergo()
